export const usersPost = [
  {
    name: "Simba Rossie",
    friendsImg: "/profile_enrique.png",
    postImg: "/img1.jpg",
    id: 1,
  },
  {
    name: "Simba Rossie",
    friendsImg: "/profile_alison.png",
    postImg: "/img2.jpg",
    id: 2,
  },
  {
    name: "Simba Rossie",
    friendsImg: "/profile_marco.png",
    postImg: "/img1.jpg",
    id: 3,
  },
  {
    name: "Simba Rossie",
    friendsImg: "/profile_martin.png",
    postImg: "/img2.jpg",
    id: 4,
  },
  {
    name: "Simba Rossie",
    friendsImg: "/profile_richard.png",
    postImg: "/img1.jpg",
    id: 5,
  },
  {
    name: "Simba Rossie",
    friendsImg: "/profile_enrique.png",
    postImg: "/img1.jpg",
    id: 1,
  },
  {
    name: "Simba Rossie",
    friendsImg: "/profile_alison.png",
    postImg: "/img2.jpg",
    id: 2,
  },
  {
    name: "Simba Rossie",
    friendsImg: "/profile_marco.png",
    postImg: "/img1.jpg",
    id: 3,
  },
  {
    name: "Simba Rossie",
    friendsImg: "/profile_martin.png",
    postImg: "/img2.jpg",
    id: 4,
  },
  {
    name: "Simba Rossie",
    friendsImg: "/profile_richard.png",
    postImg: "/img1.jpg",
    id: 5,
  },
];

export const peopleYMK = [
  {
    name: "Simba Rossie",
    img: "/profile_enrique.png",
    id: 1,
  },
  {
    name: "Simba Rossie",
    img: "/profile_alison.png",
    id: 2,
  },
  {
    name: "Simba Rossie",
    img: "/profile_marco.png",
    id: 3,
  },
  {
    name: "Simba Rossie",
    img: "/profile_martin.png",
    id: 4,
  },
  {
    name: "Simba Rossie",
    img: "/profile_richard.png",
    id: 5,
  },
  {
    name: "Simba Rossie",
    img: "/profile_enrique.png",
    id: 6,
  },
  {
    name: "Simba Rossie",
    img: "/profile_alison.png",
    id: 7,
  },
  {
    name: "Simba Rossie",
    img: "/profile_marco.png",
    id: 8,
  },
  {
    name: "Simba Rossie",
    img: "/profile_martin.png",
    id: 9,
  },
  {
    name: "Simba Rossie",
    img: "/profile_richard.png",
    id: 10,
  },
];

export const groupYML = [
  {
    name: "Software Dev",
    img: "/pic1.png",
    id: 1,
  },
  {
    name: "Data Analysis",
    img: "/pic2.png",
    id: 2,
  },
  {
    name: "Simba Rossie",
    img: "/pic3.png",
    id: 3,
  },
  {
    name: "Cyber security",
    img: "/pic4.png",
    id: 4,
  },
  {
    name: "Javascript Developers",
    img: "/pic1.png",
    id: 5,
  },
  {
    name: "Happy group",
    img: "/pic2.png",
    id: 6,
  },
];

const date = new Date();

export const allPosts = [
  {
    user_Name: "Juwon Asehinde",
    user_Img: "/profile_enrique.png",
    big_Img: "/img1.jpg",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 1,
    small_Img1: "/img1.jpg",
    small_Img2: "/img2.jpg",
    small_Img3: "pic1.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Alison Joe",
    user_Img: "/profile_alison.png",
    big_Img: "/pic1.png",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "private",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 2,
    small_Img1: "/img2.jpg",
    small_Img2: "/img1.jpg",
    small_Img3: "/pic1.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Marco John",
    user_Img: "/profile_marco.png",
    big_Img: "/img2.jpg",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "private",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 3,
    small_Img1: "/img1.jpg",
    small_Img2: "/img2.jpg",
    small_Img3: "/pic1.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Juwon Martin",
    user_Img: "/profile_martin.png",
    big_Img: "/img2.jpg",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 4,
    small_Img1: "/img1.jpg",
    small_Img2: "/img2.jpg",
    small_Img3: "/pic1.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Richard Jack",
    user_Img: "/profile_richard.png",
    big_Img: "/img2.jpg",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "private",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 5,
    small_Img1: "/img1.jpg",
    small_Img2: "/img2.jpg",
    small_Img3: "/profile_richard.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Simba Rossie",
    user_Img: "/profile_alison.png",
    big_Img: "/img1.jpg",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 6,
    small_Img1: "/img1.jpg",
    small_Img2: "/img2.jpg",
    small_Img3: "/profile_richard.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Juwon Asehinde",
    user_Img: "/profile_enrique.png",
    big_Img: "/img1.jpg",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 7,
    small_Img1: "/img1.jpg",
    small_Img2: "/img2.jpg",
    small_Img3: "/profile_richard.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
];
export const groupPosts = [
  {
    user_Name: "Juwon Asehinde",
    user_Img: "/profile_enrique.png",
    big_Img: "",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 1,
    small_Img1: "",
    small_Img2: "",
    small_Img3: "",
    comment_No: 0,
    forward_No: 28,
    like_No: 88,
  },
  {
    user_Name: "Alison Joe",
    user_Img: "/profile_alison.png",
    big_Img: "/pic1.png",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "private",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 2,
    small_Img1: "/img2.jpg",
    small_Img2: "/img1.jpg",
    small_Img3: "/pic1.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Marco John",
    user_Img: "/profile_marco.png",
    big_Img: "",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "private",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 3,
    small_Img1: "",
    small_Img2: "",
    small_Img3: "",
    comment_No: 10,
    forward_No: 8,
    like_No: 20,
  },
  {
    user_Name: "Juwon Martin",
    user_Img: "/profile_martin.png",
    big_Img: "/img2.jpg",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 4,
    small_Img1: "/img1.jpg",
    small_Img2: "/img2.jpg",
    small_Img3: "/pic1.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Richard Jack",
    user_Img: "/profile_richard.png",
    big_Img: "/img2.jpg",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "private",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 5,
    small_Img1: "/img1.jpg",
    small_Img2: "/img2.jpg",
    small_Img3: "/profile_richard.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Simba Rossie",
    user_Img: "/profile_alison.png",
    big_Img: "",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 6,
    small_Img1: "",
    small_Img2: "",
    small_Img3: "",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Juwon Asehinde",
    user_Img: "/profile_enrique.png",
    big_Img: "/img1.jpg",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 7,
    small_Img1: "/img1.jpg",
    small_Img2: "/img2.jpg",
    small_Img3: "/profile_richard.png",
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
];

export const allVideoPost = [
  {
    user_Name: "Juwon Asehinde",
    user_Img: "/profile_alison.png",
    video: "/video.2.mp4",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 1,
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Jude Daniel",
    user_Img: "/profile_enrique.png",
    video: "/video.3.mp4",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 2,
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Juwon Asehinde",
    user_Img: "/profile_alison.png",
    video: "/video.2.mp4",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 1,
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
  {
    user_Name: "Jude Daniel",
    user_Img: "/profile_enrique.png",
    video: "/video.3.mp4",
    date: `${date.toLocaleString("en-US", { month: "short" })} ${date.getDate()} at ${date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}`,
    privacy: "public",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consectetur ducimus natus. Deleniti natus voluptatem culpa, distinctio sint consectetur ipsam impedit maxime explicabo dicta quibusdam neque doloribus ipsum facilis! Et? Vitae iusto perferendis quibusdam exercitationem nam quae dolorum dolore, assumenda nihil esse qui quidem officia illum sed officiis ad veniam? Velit rerum expedita repellat sequi facilis sunt perferendis dolorum veritatis. Voluptatibus odio ut sint dicta, cumque molestiae laboriosam magnam reprehenderit commodi optio, iusto",
    id: 2,
    comment_No: 20,
    forward_No: 8,
    like_No: 80,
  },
];

export const allFriends = [
  {
    user_Name: "Juwon Asehinde",
    user_Img: "/profile_alison.png",
    id: 1,
    currentMessage: "Hello bro",
    allMessages: {},
    date: Date.now(),
  },
];


